// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bonus.sql

package sqlc

import (
	"context"
	"database/sql"
)

const listAllBonusPredictions = `-- name: ListAllBonusPredictions :many
SELECT id, category, ref_id FROM bonus_predictions
`

type ListAllBonusPredictionsRow struct {
	ID       int64                    `json:"id"`
	Category BonusPredictionsCategory `json:"category"`
	RefID    int64                    `json:"ref_id"`
}

func (q *Queries) ListAllBonusPredictions(ctx context.Context) ([]ListAllBonusPredictionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBonusPredictions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBonusPredictionsRow
	for rows.Next() {
		var i ListAllBonusPredictionsRow
		if err := rows.Scan(&i.ID, &i.Category, &i.RefID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusPredictionsForUser = `-- name: ListBonusPredictionsForUser :many
SELECT category, ref_id, points FROM bonus_predictions WHERE user_id = ?
`

type ListBonusPredictionsForUserRow struct {
	Category BonusPredictionsCategory `json:"category"`
	RefID    int64                    `json:"ref_id"`
	Points   sql.NullInt32            `json:"points"`
}

func (q *Queries) ListBonusPredictionsForUser(ctx context.Context, userID int64) ([]ListBonusPredictionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listBonusPredictionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBonusPredictionsForUserRow
	for rows.Next() {
		var i ListBonusPredictionsForUserRow
		if err := rows.Scan(&i.Category, &i.RefID, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusPredictionsWithUsers = `-- name: ListBonusPredictionsWithUsers :many
SELECT
    u.id AS user_id, u.name, u.avatar_url,
    bp.category, bp.ref_id, bp.points
FROM bonus_predictions bp
JOIN users u ON u.id = bp.user_id
ORDER BY u.name, bp.category
`

type ListBonusPredictionsWithUsersRow struct {
	UserID    int64                    `json:"user_id"`
	Name      string                   `json:"name"`
	AvatarUrl string                   `json:"avatar_url"`
	Category  BonusPredictionsCategory `json:"category"`
	RefID     int64                    `json:"ref_id"`
	Points    sql.NullInt32            `json:"points"`
}

// Every user's bonus picks with the player's name/avatar. Used to reveal others'
// picks once bonus locks at BONUS_LOCK_AT (privacy, spec §4). The INNER JOIN means
// only users who actually set picks appear. Alphabetical by player, then category.
func (q *Queries) ListBonusPredictionsWithUsers(ctx context.Context) ([]ListBonusPredictionsWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listBonusPredictionsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBonusPredictionsWithUsersRow
	for rows.Next() {
		var i ListBonusPredictionsWithUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Category,
			&i.RefID,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusResults = `-- name: ListBonusResults :many
SELECT category, ref_id FROM bonus_results
`

type ListBonusResultsRow struct {
	Category BonusResultsCategory `json:"category"`
	RefID    int64                `json:"ref_id"`
}

func (q *Queries) ListBonusResults(ctx context.Context) ([]ListBonusResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBonusResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBonusResultsRow
	for rows.Next() {
		var i ListBonusResultsRow
		if err := rows.Scan(&i.Category, &i.RefID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBonusPredictionPoints = `-- name: SetBonusPredictionPoints :exec
UPDATE bonus_predictions SET points = ? WHERE id = ?
`

type SetBonusPredictionPointsParams struct {
	Points sql.NullInt32 `json:"points"`
	ID     int64         `json:"id"`
}

func (q *Queries) SetBonusPredictionPoints(ctx context.Context, arg SetBonusPredictionPointsParams) error {
	_, err := q.db.ExecContext(ctx, setBonusPredictionPoints, arg.Points, arg.ID)
	return err
}

const upsertBonusPrediction = `-- name: UpsertBonusPrediction :exec
INSERT INTO bonus_predictions (user_id, category, ref_id)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE ref_id = VALUES(ref_id)
`

type UpsertBonusPredictionParams struct {
	UserID   int64                    `json:"user_id"`
	Category BonusPredictionsCategory `json:"category"`
	RefID    int64                    `json:"ref_id"`
}

func (q *Queries) UpsertBonusPrediction(ctx context.Context, arg UpsertBonusPredictionParams) error {
	_, err := q.db.ExecContext(ctx, upsertBonusPrediction, arg.UserID, arg.Category, arg.RefID)
	return err
}

const upsertBonusResult = `-- name: UpsertBonusResult :exec
INSERT INTO bonus_results (category, ref_id)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE ref_id = VALUES(ref_id)
`

type UpsertBonusResultParams struct {
	Category BonusResultsCategory `json:"category"`
	RefID    int64                `json:"ref_id"`
}

func (q *Queries) UpsertBonusResult(ctx context.Context, arg UpsertBonusResultParams) error {
	_, err := q.db.ExecContext(ctx, upsertBonusResult, arg.Category, arg.RefID)
	return err
}
