// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game.sql

package sqlc

import (
	"context"
)

const gameCoinBoard = `-- name: GameCoinBoard :many
SELECT u.id AS user_id, u.name, u.avatar_url, u.email,
       CAST(SUM(r.coins) AS SIGNED) AS coin_pool
FROM game_runs r JOIN users u ON u.id = r.user_id
GROUP BY u.id, u.name, u.avatar_url, u.email
ORDER BY coin_pool DESC, u.id ASC
LIMIT 20
`

type GameCoinBoardRow struct {
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
	Email     string `json:"email"`
	CoinPool  int64  `json:"coin_pool"`
}

func (q *Queries) GameCoinBoard(ctx context.Context) ([]GameCoinBoardRow, error) {
	rows, err := q.db.QueryContext(ctx, gameCoinBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCoinBoardRow
	for rows.Next() {
		var i GameCoinBoardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Email,
			&i.CoinPool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gameDistanceBoard = `-- name: GameDistanceBoard :many
SELECT u.id AS user_id, u.name, u.avatar_url, u.email,
       CAST(MAX(r.distance) AS SIGNED) AS best_distance
FROM game_runs r JOIN users u ON u.id = r.user_id
GROUP BY u.id, u.name, u.avatar_url, u.email
ORDER BY best_distance DESC, u.id ASC
LIMIT 20
`

type GameDistanceBoardRow struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	AvatarUrl    string `json:"avatar_url"`
	Email        string `json:"email"`
	BestDistance int64  `json:"best_distance"`
}

func (q *Queries) GameDistanceBoard(ctx context.Context) ([]GameDistanceBoardRow, error) {
	rows, err := q.db.QueryContext(ctx, gameDistanceBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameDistanceBoardRow
	for rows.Next() {
		var i GameDistanceBoardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Email,
			&i.BestDistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gameMeStanding = `-- name: GameMeStanding :one
SELECT CAST(COALESCE(MAX(distance),0) AS SIGNED) AS best_distance,
       CAST(COALESCE(SUM(coins),0)   AS SIGNED) AS coin_pool
FROM game_runs WHERE user_id = ?
`

type GameMeStandingRow struct {
	BestDistance int64 `json:"best_distance"`
	CoinPool     int64 `json:"coin_pool"`
}

func (q *Queries) GameMeStanding(ctx context.Context, userID int64) (GameMeStandingRow, error) {
	row := q.db.QueryRowContext(ctx, gameMeStanding, userID)
	var i GameMeStandingRow
	err := row.Scan(&i.BestDistance, &i.CoinPool)
	return i, err
}

const insertGameRun = `-- name: InsertGameRun :exec
INSERT INTO game_runs (user_id, distance, coins) VALUES (?, ?, ?)
`

type InsertGameRunParams struct {
	UserID   int64  `json:"user_id"`
	Distance uint32 `json:"distance"`
	Coins    uint32 `json:"coins"`
}

func (q *Queries) InsertGameRun(ctx context.Context, arg InsertGameRunParams) error {
	_, err := q.db.ExecContext(ctx, insertGameRun, arg.UserID, arg.Distance, arg.Coins)
	return err
}
